# Generated by Django 4.1 on 2022-09-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answered_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='asked_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
